- name: Build And Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/"               # This is correct if your index.html is in the root
    output_location: "/"            # Important: tell Azure to serve from root
    app_build_command: ""           # Disable the build step
